### ISSUE TITLE
4重forループ！

### ISSUE THREAD

**Issue by 3100** [dNaga392/aribook#12]
https://github.com/dNaga392/aribook/blob/master/src/1_1_kujibiki/solve.py#L32

さすがになんか他の方法を検討したほうが良いかと思います

**Comment by dNaga392** [comment]
導入問題ということで、蟻本の解答も４重ループだったため放置していました。
確かに公開するコードとしては品質がよくないので検討してみます。

**Comment by dNaga392** [comment]
IPython で %timeit を使用し、以下の4手法を実測しました：

4-loop : 4重forループ (is_winnable_bf)
in list : in-探索 (is_winnable_in)
binsearch : 自前実装の二分探索 (is_winnable_bs)
bisect : モジュールbisectを活用した二分探索 (is_winnable_bis)

# 実測1

蟻本のテストデータ
n=3, 戻り値:Trueの場合

データ：

```py
n = 3
m = 10
k = (1, 3, 5)
```

結果：

|         |                                          |
|---------|------------------------------------------|
|4-loop   |100000 loops, best of 3: 5.25 μs per loop|
|in list  |100000 loops, best of 3: 6.27 μs per loop|
|binsearch|100000 loops, best of 3: 7.73 μs per loop|
|bisect   |100000 loops, best of 3: 5.83 μs per loop|

# 実測2

nが最大数のテストデータ
n=50, 戻り値:Falseの場合

データ：

```py
n = 50
m = 1024
# k = tuple([random.randint(0, 100) for _ in range(n)])
k = (80, 71, 40, 95, 80, 42, 9, 25, 18, 76,
     14, 13, 81, 4, 14, 87, 96, 39, 39, 82,
     99, 7, 68, 58, 24, 34, 62, 4, 99, 100,
     79, 0, 64, 29, 68, 97, 2, 35, 29, 77,
     78, 97, 97, 30, 0, 93, 66, 6, 67, 26)
```

結果：

|         |                                      |
|---------|--------------------------------------|
|4-loop   |1 loop, best of 3: 1.6 s per loop     |
|in list  |10 loops, best of 3: 130 ms per loop  |
|binsearch|100 loops, best of 3: 16.9 ms per loop|
|bisect   |100 loops, best of 3: 2.86 ms per loop|


# まとめ

* 蟻本のテストデータでは、4重ループが最速
* n=50の場合は、bisect が最速
* nが大きくなると、二分探索は他の手法より高速であると考えられる
* 二分探索はbisectを活用したほうが、自前実装より早いことがわかる（自前実装は方法がよくないのだろう）

nが小さい場合は実行時間の差異も小さく問題とならないため、
先のコミットではnが大きい場合に高速となるbisectの実装を採用しました（検証のためソースには他の手法も残しています）。
